### ISSUE TITLE
Issues using holoport to navigate

### ISSUE THREAD

**Issue by TheLastRar** [owlboy/greatpug-public#19]
**Describe the bug**
While I don't use holoport, I been told by a couple players that they can't use holoport to navigate the pug, having to disable it or physically walk + rotate to navigate around.

**Expected behavior**
Able to navigate using holoport without issue.

**Screenshots**

**Are you in VR or Desktop mode?**
VR

**Additional context**
This used to work before, as I used to use holoport and never ran into this issue In  the past. So something changed since when I stopped using holoport to now.

**Comment by owlboy** [comment]
VRChat did an unexpected update to Holoport that appears was lightly tested. 

Holoport needs to be updated to support trigger volume configurations such as those in The Great Pug

**Comment by TheLastRar** [comment]
What are trigger volume configurations? and what are they used for in the pug

Would it not be possible to work around the issue untill VRChat fixes the cause?

**Comment by owlboy** [comment]
They are used to indicate where one can safely hold/place pickups without them respawning.

**Comment by owlboy** [comment]
They are used to indicate where one can safely hold/place pickups without them respawning.

I do not have time at the moment to implement more workarounds to paper over VRChat's bugs.

**Comment by owlboy** [comment]
They are used to indicate where one can safely hold/place pickups without them respawning.

I do not have time at the moment to implement more workarounds to paper over VRChat's bugs. I'll reassess this should it not be fixed around/shortly after the Quest build launches. The Holoport update was silently implemented into the main client as a result of changing it for Quest.

I think it was not mentioned in the patch notes because either:
• It's not finished
• It was not meant to be implemented in the main client yet (possibly because it's not finished)

**Comment by owlboy** [comment]
Please view this canny and voice your support for fixing Holoport:
https://vrchat.canny.io/bug-reports/p/holoporting-now-kills-fps-and-is-completely-broken-in-some-worlds

**Comment by owlboy** [comment]
I have received word that a solution to this has been found, and should be in a future VRChat update.

**Comment by TheLastRar** [comment]
Nice, hopefully the fix will come out soon (and without breaking anything else)

**Comment by owlboy** [comment]
@TheLastRar Has this improved with the new patch? `VRChat 2019.2.2`

**Comment by TheLastRar** [comment]
The new VRChat patch seems to have resolved the issue with holoport.
