### ISSUE TITLE
[Bug] Player local camera layer enabled on certain objects

### ISSUE THREAD

**Issue by RadiantSoul** [owlboy/greatpug-public#203]
### Describe the Bug

Using the ground IK object from Final IK to interact with the "playerlocal layer" to shoots a ray cast to interact another players local mesh also interacts with a majority of walls and floors of the world (as demonstrated by the yellow contact in this video)
https://github.com/owlboy/greatpug-public/assets/67329752/6cf9d56b-c275-4198-9aaa-f5003a26e726

### Expected Behavior

The ray cast should not interact with any part of the world

### Screenshots & Output Logs

![image](https://github.com/owlboy/greatpug-public/assets/67329752/7ce6d0f8-2e71-45c1-bb11-e267f1d50ac4)

### Are you in VR or Desktop mode?

Desktop

### Are you on Linux?

No

**Comment by owlboy** [comment]
Thanks, this should be fixed in the next build.

This is the first time anyone has pointed out a problem with using trigger volumes on this layer. These were just post-processing volumes and triggers, but they also did not need to be on that layer. I think I set most of this up back in ~2018.

Thanks again for bringing it up!
