### ISSUE TITLE
Missing Assets

### ISSUE THREAD

**Issue by WolfCoding12** [owlboy/greatpug-public#31]
**Describe the bug**
Chair assets are missing but the hitbox for the chair remains. The shelf in the lower bar is also missing but the hitbox is still there.

**To Reproduce**
Load into the great pug

**Expected behavior**
The chairs to be there and the shelf to be there

**Screenshots**
![VRChat_1920x1080_2020-02-12_20-50-51 032](https://user-images.githubusercontent.com/60998679/74403057-daf63800-4dda-11ea-8534-2bf0e4e703a1.png)

![VRChat_1920x1080_2020-02-12_20-50-52 964](https://user-images.githubusercontent.com/60998679/74403063-dfbaec00-4dda-11ea-86a5-30ba56116dcc.png)

![VRChat_1920x1080_2020-02-12_20-51-13 073](https://user-images.githubusercontent.com/60998679/74403072-e3e70980-4dda-11ea-99f8-32a0a3c5cfc3.png)

**OutputLog**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\VRChat\vrchat\` on Windows. There is currently not a simple way to get your log from an Oculus Quest HMD.

You can either attach your log to this issue report. Or link to it from http://pastebin.com

**Are you in VR or Desktop mode?**
VR

**Additional context**
None

**Comment by owlboy** [comment]
@WolfCoding12 This is likely due to using an avatar with either extra colliders on it, or a really large one. The colliders are sticking out farther than the expected player capsule by a large amount/ This causes you to hit triggers earlier than expected. It also causes you to not _exit_ triggers when expected too. 

In this case, the triggers are designed to reduce draw calls and are malfunctioning due to an unexpected and unpredictable avatar configuration.

I am considering removing the triggers in question for a variety of reasons later this evening. But do know that having avatars with unexpectedly large collider configurations will always potentially cause issues in worlds. (Things like turning on mirrors when you don't intend to, breaking optimization triggers like these, etc)

Thank for taking the time to produce this bug report! It was helpful!

**Comment by owlboy** [comment]
This was addressed in today's update. I will reassess this sort of manual occlusion sometime in the future when I've had more time with Udon.

Thank you again for reporting this.
