### ISSUE TITLE
The cursed bucket Halloween edition

### ISSUE THREAD

**Issue by Isaac1475** [owlboy/greatpug-public#41]
Is your feature request related to a problem? Please describe.
The bucket people use a modified client to put the bucket under you and then pushes you up until your game crashes.

Describe the solution you'd like
The same properties that the other object have in the world plates, bottles, etc.

Describe alternatives you've considered
None.

Additional context
Sorry for the same issue I do appreciate that you are actually fixing it I hope you have a good Halloween!

**Comment by owlboy** [comment]
What really? The bucket is on the wrong layer?

**Comment by Isaac1475** [comment]
Yes it was I'm only reporting it because I'm worried about the other players who just want to socialize like me but I'm just avoiding your world because I know that's an issue but you know what I'm going to sub to your patreon.

**Comment by owlboy** [comment]
It's cool. I jus thought I had changed it. Thank you.

I wish vrchat would warn us about situations where AASHOLES CAN BREAK EVERYTHING JUST BY USING STANDARD FEATURES. FEATURES THAT HAVE BEEN AVAILABLE SINCE 2017.


FEATURES TJAY SEEM LIKE THINGS THAT SHOULD BE FUCKIG ADDRESSED BY NOW.

What the fuck VRCHAT. _what the fuck._

I'm losing perspective? Perspective on basic features working? In Twenty fucking twenty? WHAT THE FUCK!

ITS JUST A FUCKING PICKUP. But it's not on the right layer so it means _DEATH TO USERS?_ what the fuck. Fuck you and your QA team. Fuck you.

**Comment by owlboy** [comment]
no more buckets.
