### ISSUE TITLE
Raycasting issues persisting on desktop

### ISSUE THREAD

**Issue by SplitScream** [owlboy/greatpug-public#50]
**Describe the bug**
Desktop users can't interact with objects on tables due to trigger volumes occluding raycasts

**To Reproduce**
Place a pickup on the 2nd floor table on desktop
 Try to pickup but raycast is occluded by volume trigger
 
**Expected behavior**
Users are realistically expected to be able to grab a pickup from the table

**Screenshots**
![image](https://user-images.githubusercontent.com/43389130/151252993-52e5694b-56b1-4457-8cd1-3a38baafe923.png)

**OutputLog**
Not Necessary 

**Are you in VR or Desktop mode?**
Desktop

**Additional context**
https://ask.vrchat.com/t/tutorial-how-to-fix-ray-casts/7033
I created a guide on how to fix this issue by changing the volume trigger layer to the "MirrorReflection" layer

**Comment by owlboy** [comment]
https://feedback.vrchat.com/bug-reports/p/make-desktop-user-pickup-ray-casting-work-in-situations-where-it-works-for-vr-us

A classic VRChat bug.

**Comment by owlboy** [comment]
I have pushed a build that changes the colliders involved with pickup respawning. But I don't think that will fix all of them. That table, and others, have a collider that is intended for player collision. It can't be moved to the mirrorreflection layer.

This is an [ancient](https://feedback.vrchat.com/bug-reports/p/make-desktop-user-pickup-ray-casting-work-in-situations-where-it-works-for-vr-us) VRChat bug that they managed to fix before, and then later broke. I suspect they re-broke it because the fix broke something else. And I feel the same way about the [flickering while locomoting](https://feedback.vrchat.com/bug-reports/p/1114-pickups-flicker-locally-during-locomotion) local pickup bug.

**Comment by Wasmachineman-NL** [comment]
Is it me, or has raycasting become even more broken than it was before on desktop? I can barely pick up props like the red bucket or the Voodoo Brew tumbler.

**Comment by owlboy** [comment]
@Wasmachineman-NL I have not made any changes that should cause more issues recently.

That said, the newest build that just went up may improve things.

**Comment by Wasmachineman-NL** [comment]
@owlboy Might be VRC itself that broke something.

**Comment by owlboy** [comment]
This should be fixed/greatly improved in the new build that just went up!

Thanks @hackspanner !
