### ISSUE TITLE
Night View hall chairs only usable in VR?

### ISSUE THREAD

**Issue by Wasmachineman-NL** [owlboy/greatpug-public#87]
I'm currently in VR and I noticed I could use the chairs by the windows in the Night View Hall out of nowhere. Intentional? On desktop they never worked.

**Comment by Wasmachineman-NL** [comment]
This might actually be related to the raycasting issues, come think of it.

**Comment by Wasmachineman-NL** [comment]
Apparently you can actually use them in desktop, but they're mega jank:
![VRChat_2023-04-20_22-33-45 353_3840x2400](https://user-images.githubusercontent.com/35110496/235446423-86ad9110-4113-4990-9bd2-aedef5af5903.png)

**Comment by owlboy** [comment]
Sorry for the delay on this one. It was indeed due to the ray casting issues. But I am able to work around it in this situation. And I previously was working around it. But at some point things got bumped out of alignment. It should be fixed in the next build.

I am not sure what could be causing the incorrect avatar pose though. Let me know in a new issue if that continues though. Thank you.
